provider "aws" {
  region = "${var.region}"
}

data "aws_caller_identity" "current" {}

module "alb" {
  source                                 = "../"
  vpc_id                                 = "${var.vpc_id}"
  subnets                                = "${var.subnets}"
  project                                = "${var.project}"
  environment                            = "${var.environment}"
  enable_logging                         = "${var.enable_logging}"
  force_destroy                          = "${var.force_destroy}"
  default_http_tcp_listeners_count       = "${var.default_http_tcp_listeners_count}"
  default_http_tcp_listeners_port        = "${var.default_http_tcp_listeners_port}"
  default_https_tcp_listeners_count      = "${var.default_https_tcp_listeners_count}"
  default_https_tcp_listeners_port       = "${var.default_https_tcp_listeners_port}"
  default_target_groups_count            = "${var.default_target_groups_count}"
  default_target_groups_port             = "${var.default_target_groups_port}"
  target_groups_defaults                 = "${var.target_groups_defaults}"
  default_target_groups_backend_protocol = "${var.default_target_groups_backend_protocol}"
  acm_cert_domain                        = "${var.acm_cert_domain}"
  root_domain                            = "${var.root_domain}"
  tags                                   = "${var.tags}"
  lb_accout_id_per_region                = "${var.lb_accout_id_per_region}"
  most_recent_certificate                = "${var.most_recent_certificate}"
  own_name                               = "${var.own_name}"
  own_dns_name                           = "${var.own_dns_name}"
  enable_cross_zone_load_balancing       = "${var.enable_cross_zone_load_balancing}"
  enable_deletion_protection             = "${var.enable_deletion_protection}"
  enable_http2                           = "${var.enable_http2}"
  extra_ssl_certs                        = "${var.extra_ssl_certs}"
  extra_ssl_certs_count                  = "${var.extra_ssl_certs_count}"
  idle_timeout                           = "${var.idle_timeout}"
  ip_address_type                        = "${var.ip_address_type}"
  listener_ssl_policy_default            = "${var.listener_ssl_policy_default}"
  load_balancer_create_timeout           = "${var.load_balancer_create_timeout}"
  load_balancer_delete_timeout           = "${var.load_balancer_delete_timeout}"
  load_balancer_is_internal              = "${var.load_balancer_is_internal}"
  load_balancer_update_timeout           = "${var.load_balancer_update_timeout}"
  log_location_prefix                    = "${var.log_location_prefix}"
  ports_for_security_group               = "${var.ports_for_security_group}"
}
